package com.sheng.hospital_server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
public class HospitalServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(HospitalServerApplication.class, args);
    }

}
