server:
  # 应用服务 WEB 访问端口
  port: 8081

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: 123456

  servlet:
    #文件上传配置
    multipart:
      #单个文件最大大小
      max-file-size: 10MB
      #总上传文件最大大小
      max-request-size: 100MB

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 360
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

mybatis:
  configuration:
    #日志输出到控制台 ！！！！！！！！
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true

  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mapper/*.xml

redis:
  # 过期时间 24小时
  expiration: 86400

rsa:
  # 公钥和私钥的文件路径
  public-Key-filepath: rsa/public_key.der
  private-key-filepath: rsa/private_key.der
# 注入需要改为非静态方法
#jwt:
#  secretKey: sheng
#  # 过期时间 10天
#  expire: 864000

rocketmq:
  # NameServer 地址
  name-server: 127.0.0.1:9876
  # 生产者组名
  producer:
    group: "my-boot-producer-group"